export type AppErrorCode =
  | 'UNKNOWN_ERROR'
  | 'PROJECT_NOT_FOUND'
  | 'PROJECT_LOAD_FAILED'
  | 'PROJECT_SAVE_FAILED'
  | 'DOCUMENT_IMPORT_FAILED'
  | 'DOCUMENT_NOT_FOUND'
  | 'PDF_DOCUMENT_NOT_FOUND'
  | 'PDF_PAGE_COUNT_FAILED'
  | 'PDF_RENDER_FAILED'
  | 'PDF_PREVIEW_NOT_FOUND'
  | 'PDF_PREVIEW_NOT_READY'
  | 'PDF_PREVIEW_JOB_FAILED'
  | 'PDF_UNSUPPORTED_FORMAT'
  | 'PDF_RENDERER_NOT_FOUND'
  | 'PDF_RENDERER_START_FAILED'
  | 'PDF_RENDERER_PERMISSION_DENIED'
  | 'PDF_RENDERER_OUTPUT_MISSING'
  | 'PDF_RENDERER_UNSUPPORTED'
  | 'FILE_READ_FAILED'
  | 'FILE_WRITE_FAILED'
  | 'CROP_REGION_MISSING'
  | 'WORKFLOW_BLOCKED'
  | 'EXAM_SOURCE_PDF_MISSING'
  | 'RUBRIC_DOCUMENT_MISSING'
  | 'QUESTION_COUNT_MISSING'
  | 'EXAM_PACKAGE_BUILD_PRECHECK_FAILED'
  | 'MODEL_SERVER_NOT_RUNNING'
  | 'MODEL_PROFILE_NOT_FOUND'
  | 'MODEL_PROFILE_NOT_MANAGED'
  | 'MODEL_SERVER_PATH_MISSING'
  | 'MODEL_MODEL_PATH_MISSING'
  | 'MODEL_MMPROJ_PATH_MISSING'
  | 'MODEL_PORT_ALREADY_IN_USE'
  | 'MODEL_SERVER_START_FAILED'
  | 'MODEL_SERVER_READY_TIMEOUT'
  | 'MODEL_SERVER_STOP_FAILED'
  | 'MODEL_SERVER_UNSUPPORTED_FLAGS'
  | 'MODEL_SERVER_NOT_STARTED_BY_APP'
  | 'MODEL_PROCESS_IDENTITY_MISMATCH'
  | 'MODEL_PROCESS_UNVERIFIED'
  | 'MODEL_RUNTIME_IN_USE'
  | 'MODEL_RUNTIME_DRAINING'
  | 'MODEL_RUNTIME_PROFILE_BUSY'
  | 'MODEL_RUNTIME_START_FAILED'
  | 'MODEL_RUNTIME_READINESS_TIMEOUT'
  | 'MODEL_RUNTIME_EXITED'
  | 'MODEL_RUNTIME_LEASE_INVALID'
  | 'MODEL_RUNTIME_LEASE_ALREADY_RELEASED'
  | 'MODEL_RUNTIME_PORT_OCCUPIED'
  | 'MODEL_STATE_ACCESS_FAILED'
  | 'MODEL_HEALTH_FAILED'
  | 'MODEL_PRIVACY_BLOCKED'
  | 'MODEL_EXTERNAL_CONSENT_REQUIRED'
  | 'MODEL_REDIRECT_REJECTED'
  | 'MODEL_TIMEOUT'
  | 'MODEL_RESPONSE_EMPTY'
  | 'MODEL_RESPONSE_INVALID_JSON'
  | 'MODEL_RESPONSE_INVALID_SCHEMA'
  | 'MODEL_RESPONSE_REASONING_ONLY'
  | 'OCR_FAILED'
  | 'SCORING_FAILED'
  | 'SCORING_ANCHOR_NOT_ELIGIBLE'
  | 'SCORING_ANCHOR_NOT_FOUND'
  | 'SCORING_ANCHOR_ALREADY_EXISTS'
  | 'SCORING_ANCHOR_ALREADY_REVOKED'
  | 'QEP_NOT_FROZEN'
  | 'RUBRIC_MISSING'
  | 'QUESTION_TEXT_MISSING'
  | 'QUESTION_TEXT_EXTRACTION_FAILED'
  | 'QUESTION_TEXT_SUGGESTION_NOT_FOUND'
  | 'QUESTION_TEXT_CONFIRM_FAILED'
  | 'QUESTION_TEXT_PARTIAL_SUCCESS'
  | 'RUBRIC_JSON_INVALID'
  | 'RUBRIC_JSON_PARSE_FAILED'
  | 'RUBRIC_JSON_SCHEMA_UNSUPPORTED'
  | 'RUBRIC_SCHEMA_VALIDATION_FAILED'
  | 'RUBRIC_QUESTION_NOT_FOUND'
  | 'RUBRIC_PLACEHOLDER_DETECTED'
  | 'RUBRIC_EMPTY_CONTENT'
  | 'RUBRIC_MAX_SCORE_MISSING'
  | 'RUBRIC_EXPECTED_ANSWER_MISSING'
  | 'RUBRIC_CRITERIA_MISSING'
  | 'RUBRIC_POINTS_TOTAL_MISMATCH'
  | 'RUBRIC_CONFIRM_FAILED'
  | 'RUBRIC_NOT_READY'
  | 'QUESTION_COVERAGE_INCOMPLETE'
  | 'QUESTION_LAST_ITEM_MISSING'
  | 'STUDENT_SCAN_NOT_FOUND'
  | 'STUDENT_SCAN_PREVIEW_NOT_READY'
  | 'STUDENT_GROUPING_NOT_READY'
  | 'STUDENT_GROUPING_INVALID'
  | 'STUDENT_SUBMISSION_NOT_FOUND'
  | 'STUDENT_SUBMISSION_IN_USE'
  | 'SUBMISSION_DELETE_CONFLICT'
  | 'OCR_RERUN_CANDIDATE_FAILED'
  | 'OCR_GENERATION_STALE'
  | 'OCR_GENERATION_CONFLICT'
  | 'PREVIEW_GENERATION_FAILED'
  | 'PREVIEW_GENERATION_STALE'
  | 'PREVIEW_ACTIVE_GENERATION_MISSING'
  | 'GENERATION_STILL_REFERENCED'
  | 'STUDENT_IDENTITY_INVALID'
  | 'OCR_NOT_READY'
  | 'JOB_NOT_FOUND'
  | 'PERMISSION_DENIED'
  | 'COMMAND_NOT_AVAILABLE'
  | 'MODEL_OUTPUT_RETRY_FAILED'
  | 'PROJECT_ROOT_MISMATCH'
  | 'PROJECT_ALREADY_EXISTS'
  | 'PROJECT_DIRECTORY_NOT_EMPTY'
  | 'PROJECT_MIGRATION_REQUIRED'
  | 'UNSAFE_MANAGED_PATH'
  | 'MANAGED_PATH_OUTSIDE_PROJECT'
  | 'MANAGED_PATH_SYMLINK_ESCAPE'
  | 'LEGACY_DOCUMENT_PATH_UNRESOLVED'
  | 'PROJECT_REVISION_CONFLICT'
  | 'PROJECT_EXTERNALLY_MODIFIED'
  | 'PROJECT_MUTATION_CONFLICT'
  | 'PROJECT_ENTITY_STALE'
  | 'PROJECT_ENTITY_NOT_FOUND'
  | 'PROJECT_MUTATION_REJECTED';

export type AppError = {
  code: AppErrorCode;
  safeMessage: string;
  recoveryAction?: string;
  correlationId: string;
  retryable: boolean;
  detailsAvailable: boolean;
};

export const projectConflictCodes: ReadonlySet<AppErrorCode> = new Set([
  'PROJECT_REVISION_CONFLICT',
  'PROJECT_EXTERNALLY_MODIFIED',
  'PROJECT_MUTATION_CONFLICT',
  'PROJECT_ENTITY_STALE',
]);

export function isProjectConflictError(
  error: Pick<AppError, 'code'> | null | undefined,
): boolean {
  return error ? projectConflictCodes.has(error.code) : false;
}

export function isProjectMigrationRequiredError(
  error: Pick<AppError, 'code'> | null | undefined,
): boolean {
  return error?.code === 'PROJECT_MIGRATION_REQUIRED';
}

const UNKNOWN_ERROR_SAFE_MESSAGE = 'Bilinmeyen bir hata oluştu.';

export function isAppError(e: unknown): e is AppError {
  if (typeof e !== 'object' || e === null) return false;
  const candidate = e as Record<string, unknown>;
  if (typeof candidate.code !== 'string') return false;
  if (typeof candidate.safeMessage !== 'string') return false;
  if (
    candidate.recoveryAction !== undefined &&
    typeof candidate.recoveryAction !== 'string'
  ) {
    return false;
  }
  return true;
}

export function normalizeAppError(e: unknown): AppError {
  if (isAppError(e)) return e;
  return {
    code: 'UNKNOWN_ERROR',
    safeMessage: UNKNOWN_ERROR_SAFE_MESSAGE,
    recoveryAction: undefined,
    correlationId: crypto.randomUUID?.() || 'unknown',
    retryable: false,
    detailsAvailable: false,
  };
}
